# Generated by Django 4.1.1 on 2023-01-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Operations",
        ),
    ]
