# Generated by Django 4.1.1 on 2023-01-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("Idser", models.AutoField(primary_key=True, serialize=False)),
                ("Input", models.CharField(max_length=500)),
                ("Output", models.CharField(max_length=500)),
                ("Processnumber", models.IntegerField()),
                ("Flag", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Operations",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="Gender",
            field=models.CharField(max_length=6),
        ),
        migrations.AddField(
            model_name="relation",
            name="SerId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.services"
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="UserId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
            ),
        ),
    ]
