# Generated by Django 4.1.1 on 2023-01-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_remove_relation_serid_delete_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Input", models.CharField(max_length=500)),
                ("Output", models.CharField(max_length=500)),
                ("Processnumber", models.IntegerField()),
                ("Flag", models.IntegerField()),
            ],
        ),
    ]
