# Generated by Django 4.1.1 on 2023-01-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_service"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
