# Generated by Django 4.1.1 on 2023-01-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_delete_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relation",
            name="UserId",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Relation",
        ),
    ]
