# Generated by Django 4.1.1 on 2023-01-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0010_remove_relation_serid_remove_relation_userid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=80)),
                ("LastName", models.CharField(max_length=80)),
                ("Gender", models.CharField(max_length=6)),
                ("Country", models.CharField(max_length=50)),
                ("City", models.CharField(max_length=50)),
                ("Specialist", models.CharField(max_length=80)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=11)),
                ("Password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Input", models.CharField(max_length=500)),
                ("Output", models.CharField(max_length=500)),
                ("Processnumber", models.IntegerField()),
                ("Flag", models.IntegerField()),
                (
                    "Doctors",
                    models.ManyToManyField(
                        through="doctor.Relation", to="doctor.doctor"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relation",
            name="SerId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.service"
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="UserId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
            ),
        ),
    ]
