# Generated by Django 4.1.1 on 2023-02-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0014_remove_relation_serid_remove_relation_userid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=80)),
                ("LastName", models.CharField(max_length=80)),
                ("Gender", models.CharField(max_length=6)),
                ("Region", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=11)),
                ("Password", models.CharField(max_length=50)),
                ("Input", models.ImageField(upload_to="input/%y/%m/%d")),
            ],
        ),
    ]
