# Generated by Django 4.1.1 on 2023-02-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0015_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="Input",
            field=models.ImageField(
                upload_to="<django.db.models.fields.EmailField>/input/%y/%m/%d"
            ),
        ),
    ]
