# Generated by Django 4.1.1 on 2023-02-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0017_rename_firstname_doctor_name_remove_doctor_lastname_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"ordering": ["Name"]},
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="Input",
        ),
    ]
