# Generated by Django 4.1.1 on 2023-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0020_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="Processnumber",
            field=models.CharField(default="1", max_length=500),
        ),
    ]
