# Generated by Django 4.1.1 on 2023-02-04 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0021_alter_service_processnumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="Doctors",
        ),
        migrations.AddField(
            model_name="doctor",
            name="SerId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.service",
            ),
        ),
        migrations.DeleteModel(
            name="Relation",
        ),
    ]
