# Generated by Django 4.1.1 on 2023-02-04 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor", "0023_remove_doctor_serid_relation_service_doctors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Input", models.ImageField(upload_to="input/%y/%m/%d")),
                ("Output", models.CharField(max_length=500)),
                ("Processnumber", models.CharField(default="1", max_length=500)),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name="relation",
            name="SerId",
        ),
        migrations.RemoveField(
            model_name="relation",
            name="UserId",
        ),
        migrations.RemoveField(
            model_name="service",
            name="Doctors",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Relation",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
