# Generated by Django 4.1.1 on 2023-02-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0024_operation_remove_relation_serid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="Input",
            field=models.ImageField(upload_to="input"),
        ),
    ]
