# Generated by Django 4.1.5 on 2023-03-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_alter_operation_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
