# Generated by Django 4.1.5 on 2023-05-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_alter_operation_cnv_alter_operation_dme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='OPID',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
