# Generated by Django 4.1.5 on 2023-05-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_operation_opid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='OPID',
            field=models.IntegerField(default=1),
        ),
    ]
