# Generated by Django 4.1.5 on 2023-06-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0032_remove_operation_opid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="Normal",
            new_name="Cataract",
        ),
        migrations.AddField(
            model_name="operation",
            name="Diabetes",
            field=models.CharField(default="0", max_length=8),
        ),
        migrations.AddField(
            model_name="operation",
            name="Glaucoma",
            field=models.CharField(default="0", max_length=8),
        ),
        migrations.AddField(
            model_name="operation",
            name="Hypertension",
            field=models.CharField(default="0", max_length=8),
        ),
        migrations.AddField(
            model_name="operation",
            name="Macular_Degeneration",
            field=models.CharField(default="0", max_length=8),
        ),
        migrations.AddField(
            model_name="operation",
            name="Normal_Macular",
            field=models.CharField(default="0", max_length=8),
        ),
        migrations.AddField(
            model_name="operation",
            name="Normal_OCT",
            field=models.CharField(default="0", max_length=8),
        ),
        migrations.AddField(
            model_name="operation",
            name="Other",
            field=models.CharField(default="0", max_length=8),
        ),
        migrations.AddField(
            model_name="operation",
            name="Pathological_Myopia",
            field=models.CharField(default="0", max_length=8),
        ),
    ]
