# Generated by Django 4.1.5 on 2023-06-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0033_rename_normal_operation_cataract_operation_diabetes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="Macular_Degeneration",
            new_name="MacularDegeneration",
        ),
        migrations.RenameField(
            model_name="operation",
            old_name="Normal_Macular",
            new_name="NormalMacular",
        ),
        migrations.RenameField(
            model_name="operation",
            old_name="Normal_OCT",
            new_name="NormalOCT",
        ),
        migrations.RenameField(
            model_name="operation",
            old_name="Pathological_Myopia",
            new_name="PathologicalMyopia",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="Processnumber",
        ),
        migrations.AddField(
            model_name="operation",
            name="ProcessName",
            field=models.CharField(default="OCT", max_length=65),
        ),
    ]
