# Generated by Django 4.1.5 on 2023-06-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "doctor",
            "0034_rename_macular_degeneration_operation_maculardegeneration_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="NormalOCT",
            new_name="Normal",
        ),
    ]
