# Generated by Django 4.1.5 on 2023-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_rename_normal_operation_normaloct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Output',
            field=models.CharField(max_length=255),
        ),
    ]
